config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :events do

    member do
      get :dashboard
    end

    collection do
      get :latest
      get :popular

      post :bulk_update
      post :bulk_delete
    end

    resources :attendees
    resource :detail, :controller => "event_details"

  end

  namespace :admin do
    resources :events
  end

  resources :people

  get 'welcome/say_hello' => 'welcome#say'

  get 'welcome' => 'welcome#index'

  post 'next_step' => 'welcome#next_step', :as => :next_step
  post 'final_step' => 'welcome#final_step', :as => :final_step

  root 'welcome#index'

end

app/models/attendee.rb
class Attendee < ActiveRecord::Base

  validates_presence_of :name, :event_id

  belongs_to :event

end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController

  before_action :authenticate_user!

  before_action :set_event

  def index
    @attendees = @event.attendees
  end

  def show
    @attendee = @event.attendees.find( params[:id] )
  end

  def new
    @attendee = @event.attendees.build
  end

  def create
    @attendee = @event.attendees.build( attendee_params )

    if @attendee.save
      redirect_to event_attendees_path(@event)
    else
      render :new
    end
  end

  def edit
    @attendee = @event.attendees.find( params[:id] )
  end

  def update
    @attendee = @event.attendees.find( params[:id] )

    if @attendee.update( attendee_params )
      redirect_to event_attendees_path(@event)
    else
      render :edit
    end
  end

  def destroy
    @attendee = @event.attendees.find( params[:id] )

    @attendee.destroy

    redirect_to event_attendees_path(@event)
  end

  protected

  def attendee_params
    params.require(:attendee).permit(:name, :email)
  end

end

app/helpers/attendees_helper.rb
module AttendeesHelper
end

app/views/attendees/_form.html.erb
<% if @attendee.errors.any? %>
      <ul>
      <% @attendee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
<% end %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.submit "送出", :class => "btn btn-primary" %>

app/views/attendees/edit.html.erb
<%= form_for @attendee, :url => event_attendee_path(@event, @attendee) do |f| %>

  <%= render :partial => "form", :locals => { :f => f } %>

<% end %>

app/views/attendees/index.html.erb
<h2><%= @event.name %> 報名列表</h2>


<table class="table table-bordered">
  <% @attendees.each do |a| %>
    <tr>
      <td><%= a.name %></td>
      <td>

        <%= link_to "詳細頁面", event_attendee_path(@event, a), :class => "btn btn-primary" %>

        <%= link_to "編輯", edit_event_attendee_path(@event, a), :class => "btn btn-primary" %>

        <%= link_to "刪除", event_attendee_path(@event, a), :method => "delete", :class => "btn btn-danger" %>

      </td>
    </tr>
  <% end %>
</table>

<%= link_to "新增", new_event_attendee_path(@event), :class => "btn btn-primary" %>

app/views/attendees/new.html.erb
<%= form_for @attendee, :url => event_attendees_path(@event) do |f| %>

  <%= render :partial => "form", :locals => { :f => f } %>

<% end %>

app/views/attendees/show.html.erb
<p>Name: <%= @attendee.name %></p>
<p>Email: <%= @attendee.email %></p>


<%= link_to "Back to Attendee List", event_attendees_path(@event) %>