config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :events do

    member do
      get :dashboard
    end

    collection do
      get :latest
      get :popular

      post :bulk_update
      post :bulk_delete
    end

    resources :attendees
    resource :detail, :controller => "event_details"

  end

  namespace :admin do
    resources :events
  end

  resources :people

  get 'welcome/say_hello' => 'welcome#say'

  get 'welcome' => 'welcome#index'

  post 'next_step' => 'welcome#next_step', :as => :next_step
  post 'final_step' => 'welcome#final_step', :as => :final_step

  root 'welcome#index'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  # app/views/welcome/say.html.erb
  def say
  end

  def index
  end

  def next_step
  end

  def final_step
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_first_step.html.erb
<%= form_tag next_step_path, :remote => true do %>
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <h4 class="modal-title" id="myModalLabel">Modal title</h4>
</div>
<div class="modal-body">

  This is first modal at HTML.

</div>
<div class="modal-footer">
  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
  <%= submit_tag "Save changes", :class => "btn btn-primary" %>
</div>
<% end %>

app/views/welcome/_next_step.html.erb
<%= form_tag final_step_path, :remote => true do %>
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <h4 class="modal-title" id="myModalLabel">Modal title</h4>
</div>
<div class="modal-body">

  This is step two.

</div>
<div class="modal-footer">
  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
  <%= submit_tag "Save changes", :class => "btn btn-primary" %>
</div>
<% end %>

app/views/welcome/final_step.js.erb
$('#myModal').modal("hide");

// reset modal to first step after 0.5s
setTimeout(function(){
  var content = "<%= j( render :partial => 'first_step' ) %>";
  $("#model-content").html(content);
}, 500)

app/views/welcome/index.html.erb
<%= I18n.locale %>

<hr>

<p>Hola! It's <%= Time.now %></p>

<%= t(:hello_world) %>

<%= t("hello", :name => "ihower") %>

<%= link_to "Say Hello", welcome_say_hello_path %>

<hr>

<!-- Button trigger modal -->
<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
  Launch demo modal
</button>

<!-- Modal -->
<div id="myModal" class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div id="model-content" class="modal-content">

      <%= render "first_step" %>

    </div>
  </div>
</div>

app/views/welcome/next_step.js.erb
var content = "<%= j( render :partial => 'next_step' ) %>";
$("#model-content").html(content);

app/views/welcome/say.html.erb
<h1>Hello, World!</h1>