config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :events do

    member do
      get :dashboard
    end

    collection do
      get :latest
      get :popular

      post :bulk_update
      post :bulk_delete
    end

    resources :attendees
    resource :detail, :controller => "event_details"

  end

  namespace :admin do
    resources :events
  end

  resources :people

  get 'welcome/say_hello' => 'welcome#say'

  get 'welcome' => 'welcome#index'

  post 'next_step' => 'welcome#next_step', :as => :next_step
  post 'final_step' => 'welcome#final_step', :as => :final_step

  root 'welcome#index'

end

app/models/event.rb
class Event < ActiveRecord::Base

  attr_accessor :_destory_logo

  STATUS = ["published", "draft"]

  validates_presence_of :name, :friendly_id

  validates_uniqueness_of :friendly_id

  belongs_to :user
  belongs_to :category

  has_many :attendees, :dependent => :destroy

  has_many :event_groupships, :dependent => :destroy

  has_many :groups, :through => :event_groupships

  has_one :detail, :class_name => "EventDetail", :dependent => :destroy

  accepts_nested_attributes_for :detail, :allow_destroy => true, :reject_if => :all_blank

  has_attached_file :logo, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :logo, :content_type => /\Aimage\/.*\Z/

  before_validation :setup_friendly_id

  before_validation :remove_logo

  has_many :taggings
  has_many :tags, :through => :taggings

  def to_param
    self.friendly_id
  end

  def tag_list
    self.tags.map{ |t| t.name }.join(",")
  end

  def tag_list=(value)
    tags = value.split(",").map { |tag_name|
      tag_name = tag_name.strip
      Tag.find_by_name(tag_name) || Tag.create( :name => tag_name)
    }

    self.tag_ids = tags.map{ |x| x.id }
  end

  def author_name
    if user
      user.display_name
    else
      I18n.t("nobody")
    end
  end

  def remove_logo
    if self._destory_logo
      self.logo = nil
    end
  end

  def setup_friendly_id
    if self.friendly_id.blank?
     self.friendly_id = SecureRandom.hex(8)
    end
  end

end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController

  before_action :authenticate_user!
  before_action :check_admin

  def index
    @events = Event.all
  end

  protected

  def check_admin
    unless current_user.admin?
      flash[:alert] = "Nooooooooooo!"
      redirect_to root_path
      return
    end
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :authenticate_user!

  before_action :set_event, :only => [:show, :edit, :update, :destroy, :dashboard]

  # URL Helpers:
  #   events_path
  #   event_path(e)
  #   new_event_path
  #   edit_event_path(e)

  # GET /events
  def index

    load_events

    @event = Event.new
    @event.setup_friendly_id

    load_gon_tags

    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @events.to_xml }
      format.json { render :json => @events.to_json }
      format.atom { @feed_title = "My event list" } # index.atom.builder
    end
  end

  def new
    @event = Event.new
    load_gon_tags
  end

  def latest
    @events = Event.order("id DESC").limit(3)
  end

  def popular
  end

  # GET /events/123
  def show
    @title = @event.name
  end

  def dashboard
  end

  # POST /events
  def create
    @event = Event.new( event_params )

    @event.user = current_user

    if @event.save

      flash[:notice] = I18n.t("create_successful")

      redirect_to events_path
    else
      load_events
      load_gon_tags
      render :action => :index
    end
  end

  # GET /events/123/edit
  def edit
    load_gon_tags
  end

  # PATCH /events/123
  def update
    if @event.update( event_params )

      flash[:notice] = "編輯成功"

      redirect_to events_path
    else
      load_gon_tags
      render :action => :edit
    end
  end

  # DELETE /events/123
  def destroy
    @event.destroy

    flash[:alert] = "Done 刪除!!"

    redirect_to events_path
  end

  def bulk_update
    events = params[:ids].map{ |x| Event.find(x) }

    events.each do |x|
      if params["btn-delete"]
        x.destroy
      elsif params["btn-publish"]
        x.update( :status => "published" )
      end
    end

    redirect_to events_url
  end

  def bulk_delete
    #Event.destroy_all
    Event.first.destroy

    flash[:alert] = "砍了!"
    redirect_to events_url
  end

  private

  def load_events
    if params[:category_id]
      @category = Category.find( params[:category_id] )
      @events = @category.events.page( params[:page] ).per(3)
    else
      @events = Event.page( params[:page] ).per(3)
    end

    if params[:order] == "created_at_desc"
      @events = @events.order("created_at DESC")
    end

    if params[:keyword]
      @events = @events.where( [ "name like ?", "%#{params[:keyword]}%" ] )
    end

    @categories = Category.all
  end

  def set_event
    @event = Event.find_by_friendly_id( params[:id] )
  end

  def event_params
    params.require(:event).permit(:name, :tag_list, :_destory_logo, :description, :friendly_id, :status, :published_at, :due_date, :category_id, :logo, :detail_attributes => [:information, :_destroy, :id], :group_ids => [] )
  end

  def load_gon_tags
    gon.tags = Tag.pluck(:name)
  end

end

app/views/events/_form.html.erb
<% if @event.errors.any? %>
      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
<% end %>

<div class="form-group">
  <%= f.label :name, "名稱" %>
  <%= f.text_field :name, :placeholder => "Event name", :class=> "form-control" %>
</div>

<div class="form-group">
  <%= f.label :friendly_id, "http://XXX/events/" %>
  <%= f.text_field :friendly_id, :class=> "form-control" %>
</div>

<div class="form-group">
  <%= f.label :tag_list, "標籤" %>
  <%= f.text_field :tag_list, :placeholder => "tag1, tag2", :class=> "form-control", :id => "tagging-list" %>

</div>

<div class="form-group">
  <%= f.label :category_id, "分類" %>
  <%= f.select :category_id, Category.all.map{ |x| [ x.name, x.id] },  :include_blank => "請選擇!" %>

  <%#= f.collection_select(:category_id, Category.all, :id, :name,  { :prompt => "Please select a cateogry..." } ) %>

</div>

<div class="form-group">
  <%= f.label :group_ids, "分組" %>
  <%#= f.collection_check_boxes(::group_ids, Group.all, :id, :name) %>

  <%= f.select :group_ids, Group.all.map{ |g| [g.name, g.id] }, {}, :multiple => true, :id => "multiple-group-select", :class=> "form-control" %>

</div>

<div class="form-group">
  <%= f.label :status, "狀態" %>
  <%= f.select :status, event_status_options %>
</div>

<div class="form-group">
  <%= f.label :description, "內容" %>
  <%= f.text_area :description, :class=> "form-control" %>
</div>

<div class="form-group">
  <%= f.label :published_at, "發布時間" %>
  <%= f.datetime_select :published_at %>
</div>

<div class="form-group">
  <%= f.label :logo, "LOGO檔案" %>
  <%= f.file_field :logo %>

  <%#= f.check_box :_destory_logo %>

  <%= check_box_tag "event[_destroy_logo]" %>

  移除照片

</div>

<div class="form-group">
  <%= f.label :due_date, "截止日期" %>
  <%#= f.date_select :due_date %>

  <%= f.text_field :due_date, :class => "datepicker" %>

</div>

<%= f.fields_for :detail do |f2| %>

<div class="form-group">
  <%= f2.label :information, "Information" %>
  <%= f2.text_field :information %>

  <% unless f2.object.new_record? %>
    <%= f2.label :_destroy, 'Remove:' %>
    <%= f2.check_box :_destroy %>
  <% end %>


</div>

<% end %>

<div class="form-group">
  <%= f.submit "送出", :class => "btn btn-primary" %>
</div>

<%= Gon::Base.render_data({}) %>
<script>

  $('.datepicker').datepicker({
     format: "yyyy/mm/dd"
  });


  $("#multiple-group-select").select2();

  $("#tagging-list").select2({
    tags: gon.tags,
    tokenSeparators: [',', ' ']
  });

</script>

app/views/events/dashboard.html.erb
<h2><%= @event.name %>'s Dashboard</h2>

app/views/events/edit.html.erb
<h2>Edit event</h2>

<%= form_for build_event(@event), :url => event_path(@event), :method => :patch do |f| %>

  <%= render :partial => "form", :locals => { :f => f } %>

<% end %>

app/views/events/index.html.erb
<h1><%= t("event", :scope => "admin") %></h1>

<div id="event_form">
<%= form_for @event, :url => events_path do |f| %>
  <%= render :partial => "form", :locals => { :f => f } %>
<% end %>
</div>

<%= form_tag events_path, :method => :get do %>
    <%= text_field_tag "keyword" %>
  <%= submit_tag "Search" %>
<% end %>

<p>
<%= link_to "Latest", latest_events_path %>
<%= link_to "Popular", popular_events_path %>
</p>

<p>
  Order by: <%= link_to "最新遞降", events_path( merge_event_filters(params, :order => "created_at_desc") ) %> |

  <%= link_to "最新遞增", events_path( merge_event_filters(params, :order => "") ) %>

</p>

<p>
<% @categories.each do |c| %>
  <%= link_to c.name, events_path( merge_event_filters(params, :category_id => c.id) ) %>
<% end %>

  <%= link_to "All", events_path %>
</p>

<%= form_tag bulk_update_events_path do %>

<table class="table table-bordered">
<% @events.each do |e| %>

  <tr>
    <td>
      <%= check_box_tag "ids[]", e.id, false %>
      <%= e.name %>
    </td>
    <td><%= e.category.try(:name) %></td>
    <td>

<%= link_to "主控台", dashboard_event_path(e), :class => "btn btn-primary" %>

    <%= link_to "顯示", event_path(e), :class => "btn btn-primary" %>

<%= link_to '詳細', event_detail_path(e), :class => "btn btn-primary" %>


 <%= link_to "報名者列表", event_attendees_path(e), :class => "btn btn-primary" %>


    <%= link_to "編輯", edit_event_path(e), :class => "btn btn-default" %>

    <%= link_to event_path(e), :data => { :confirm => "Are you sure?" } , :method => :delete, :class => "btn btn-danger" do %>
      <%= icon("remove") %> 刪除
    <% end %>
    </td>
  </tr>

<% end %>
</table>

  <%= submit_tag "刪除", :name => "btn-delete" %>

  <%= submit_tag "Publish", :name => "btn-publish" %>

<% end %>

<%= paginate @events %>

<%= link_to "#", :id => "event-form-show", :class => "btn btn-primary" do %>
  <%= icon("plus") %> 新增活動
<% end %>

<p>
  <%= link_to "XML", events_path( :format => :xml) %>
|
  <%= link_to "JSON", events_path( :format => :json) %>
</p>

<p>
<%= button_to "Delete all", bulk_delete_events_path %>
</p>

<script>

  <% unless @event.errors.any? %>
    $("#event_form").hide();
  <% end %>

  $("#event-form-show").click(function(){
    $("#event_form").toggle();
  })
</script>

app/views/events/latest.html.erb
<script>
  $(function(){
    $(".desc").hide();

    $("a").click(function(){
      var div = $(this).parent()
      var h2 = div.find("h2");
      var event_name = div.data("ename");

      div.find(".desc").toggle();

      h2.toggleClass("highlight");

      if ( h2.hasClass("highlight") ) {
        var d = div.data("edate");
        h2.text(event_name + d);
      } else {
        h2.text(event_name);
      }
    })
  })
</script>

<h1>Latest Event</h1>

<% @events.each do |event| %>
<div data-ename="<%= event.name %>" data-edate="<%= event.published_at.to_s(:short) %>">

  <h2><%= event.name %></h2>

  <p class="desc"><%= event.description %></p>
  <a href="#">Toggle</a>
</div>
<% end %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= form_for build_event(@event), :url => events_path do |f| %>

  <%= render :partial => "form", :locals => { :f => f } %>

<% end %>

app/views/events/popular.html.erb
<h2>Popular</h2>

app/views/events/show.html.erb
<h1><%= @event.name %></h1>

<% if @event.logo.exists? %>

  <%= image_tag( @event.logo(:thumb) ) %>

<% end %>

<p>截止日期: <%= @event.due_date %></p>

<p>發布時間: <%= @event.published_at.to_s(:long) %></p>

<p>建立人: <%= @event.author_name %></p>

<p>狀態: <%= @event.status %></p>

<p>分組:

<%= @event.groups.map{ |g| g.name }.join(", ") %>


</p>


<p>

  <%= simple_format( @event.description ) %>
</p>

<h2>Attendee List</h2>

<% @event.attendees.each do |a| %>
  <p><%= a.name %></p>
<% end %>

<%= link_to "活動列表", events_path %>